stages:
  - package

package-job:
  tags:
    - market-plus-shell
  stage: package
  only:
    - develop
  script:
    - yarn
    - yarn build:dev
    - cp -a ./dist /root/4paradigm/market/touch-front
    - docker rm -f market-touch
    - docker build -t market-touch:1.0 .
    - docker run --name market-touch -d -p 18707:80 market-touch:1.0
