stages:
  - package

package-job:
  tags:
    - market-plus-shell
  stage: package
  only:
    - develop
  script:
    - pnpm
    - pnpm build:dev
    - cp -a ./dist /root/4paradigm/market/touch-front

